<?php
/**
 * Created by PhpStorm.
 * User: lee
 * Date: 2017/1/19
 * Time: 19:55
 */

namespace App\Admin\Extensions;
use App\Admin\Service\DynamicAttribute;
use Encore\Admin\Form\Field;

class Category extends Field
{
    protected $view = 'admin.fields.category';
    protected $elementClass = 'category';
    protected static $css = [
    ];

    protected static $js = [
    ];

    protected $attributes = [
        'data-level'=>'0',
    ];

    public function render()
    {
        $source = '/';
        $this->variables['rootOptions'] = DynamicAttribute::getRootOptions();
        $this->script = <<<EOT
                var CategoryMan = {
                        container:$('.category-container'),
                        clearGarbage:function(level){
                            //clear them
                            $('.category').each(function(index,target){
                                     if($(target).data('level') > level) 
                                     {
                                            $(target).remove();
                                     }
                            });
                        },
                        makeSelect:function(level,data){
                             //make select,get the level
                             var newLevel = level + 1;
                             
                             //append select to container
                             var newSelect = '<select class="form-control category" style="width: 100%;" name="category[]" >';
                             newSelect+=this.makeOptions(data);
                             newSelect+="</select>";
                             newSelect = $(newSelect); 
                             newSelect.data('level',newLevel);
                             
                             //inject data
                             newSelect.appendTo(this.container);
                        },
                        makeOptions:function(data){
                            var html = '';
                            for(item in data){
                                html+= '<option value="'+ data[item].id + '">' + data[item].title + '</option>';
                            }
                            return html;
                        },
                        
                };
                var CategoryEvent = function(){
                        //get level
                        var level = $(this).data('level');
                        //get select option
                        var value = this.value;
                        CategoryMan.clearGarbage(level);
                        //$.get("$source/"+value,function(data){
                        data = [{id:9,title:'shit'},{id:10,title:'fuck'}];
                            if(data == 'over') 
                            {
                                return;
                            }else{
                                CategoryMan.makeSelect(level,data);
                            }
                        //});
                        $('.category').unbind();
                        $('.category').bind('change',CategoryEvent);
                };
                $('.category').change(CategoryEvent);
EOT;

        return parent::render(); // TODO: Change the autogenerated stub
    }
}